type TextAlignType = "start" | "end" | "left" | "right" | "center" | "justify" | "match-parent" | undefined

export interface StyleInterface {
  // global
  allPluginFontFamily: undefined|string,
  allPluginFontSize: undefined|string,
  allPluginFontWeight: undefined|number|string,
  allPluginColor: undefined|string,
  allPluginBackground: undefined|string,
  // table borders
  tableBodyVerticalBorder: undefined|string,
  tableBodyHorizontalBorder: undefined|string,
  tableHeadVerticalBorder: undefined|string,
  tableHeadHorizontalBorder: undefined|string,
  tableCellVerticalBorder: undefined|string,
  tableCellHorizontalBorder: undefined|string,
  moreInfoTableHorizontalBorder: undefined|string,
  // table background color
  tableHeadBackground: undefined|string,
  tableBodyBackground: undefined|string,
  tableOddRowBackground: undefined|string,
  tableSortedColumnBackground: undefined|string,
  tableSortedColumnOddRowBackground: undefined|string,
  tableHoveredRowBackground: undefined|string,
  tableSortedColumnHoveredRowBackground: undefined|string,
  moreInfoTableBackground: undefined|string,
  // table text
  tableCellPadding: undefined|string,
  tableHeadTextAlign: TextAlignType,
  tableBodyTextAlign: TextAlignType,
  tableBodyFontFamily: undefined|string,
  tableHeadFontFamily: undefined|string,
  tableBodyFontSize: undefined|string,
  tableHeadFontSize: undefined|string,
  tableBodyFontWeight: undefined|number|string,
  tableHeadFontWeight: undefined|number|string,
  tableBodyColor: undefined|string,
  tableHeadColor: undefined|string,
  // moreInfoTable text
  moreInfoTableMarginLeft: undefined|string,
  moreInfoTableCellPadding: undefined|string,
  moreInfoTableBodyFontFamily: undefined|string,
  moreInfoTableHeadFontFamily: undefined|string,
  moreInfoTableBodyFontSize: undefined|string,
  moreInfoTableHeadFontSize: undefined|string,
  moreInfoTableBodyFontWeight: undefined|number|string,
  moreInfoTableHeadFontWeight: undefined|number|string,
  moreInfoTableBodyColor: undefined|string,
  moreInfoTableHeadColor: undefined|string,
  // selectPage buttons
  selectPageFontFamily: undefined|string,
  selectPageFontSize: undefined|string,
  selectPageFontWeight: undefined|number|string,
  selectPageButtonColor: undefined|string,
  selectPageButtonBorder: undefined|string,
  selectPageButtonBorderRadius: undefined|string,
  selectPageButtonBackground: undefined|string,
  selectPageButtonDisabledBorder: undefined|string,
  selectPageButtonDisabledBackground: undefined|string,
  selectPageButtonDisabledColor: undefined|string,
  selectPageButtonActiveBorder: undefined|string,
  selectPageButtonActiveBackground:
  undefined|string,
  selectPageButtonActiveColor: undefined|string,
  selectPageButtonHoveredBorder: undefined|string,
  selectPageButtonHoveredBackground:
  undefined|string,
  selectPageButtonHoveredColor: undefined|string,
  // selectItemsPerPage
  selectItemsPerPageFontFamily: undefined|string,
  selectItemsPerPageFontSize: undefined|string,
  selectItemsPerPageFontWeight: undefined|number|string,
  selectItemsPerPageColor: undefined|string,
  selectItemsPerPageSelectBackground: undefined|string,
  selectItemsPerPageSelectColor: undefined|string,
  selectItemsPerPageSelectBorder: undefined|string,
  selectItemsPerPageSelectBorderRadius: undefined|string,
  // filter
  filterFontFamily: undefined|string,
  filterFontSize: undefined|string,
  filterFontWeight: undefined|number|string,
  filterColor: undefined|string,
  filterInputBackground: undefined|string,
  filterInputColor: undefined|string,
  filterInputBorder: undefined|string,
  filterInputBorderRadius: undefined|string,
  // showDisplayedItems
  showDisplayedItemsFontFamily: undefined|string,
  showDisplayedItemsFontSize: undefined|string,
  showDisplayedItemsFontWeight: undefined|number|string,
  showDisplayedItemsColor: undefined|string,
};
