export const defaultStyle = {
  //global
  AllPluginFontFamily: 'inherit',
  AllPluginFontSize: 'inherit',
  AllPluginColor: 'inherit',
  AllPluginBackground: 'none',
  //table borders
  tableBodyVerticalBorder: undefined,
  tableBodyHorizontalBorder: '1px solid #000',
  tableHeaderVerticalBorder: undefined,
  tableHeaderHorizontalBorder: undefined,
  tableCellsVerticalBorder: undefined,
  tableCellsHorizontalBorder: '1px solid #DDD',
  //table background color
  tableHeaderBackground: '#FFF',
  tableBodyBackground: '#FFF',
  tableEvenRowBackground: '#F9F9F9',
  tableSortedColumnBackground: '#F1F1F1',
  tableHoveredRowBackground: '#F1F1F1',
  tableSortedHoveredRowBackground: '#EAEAEA',
  //table text
  tableCellPadding: '0.5rem 1rem',
  tableHeadingCellTextAlignement: 'center',
  tableBodyCellTextAlignement: 'left',
  tableBodyCellFontFamily: 'inherit',
  tableHeaderCellFontFamily: 'inherit',
  tableBodyCellFontSize: 'inherit',
  tableHeaderCellFontSize: 'inherit',
  tableBodyCellFontWeight: undefined,
  tableHeaderCellFontWeight: undefined,
  tableBodyCellColor: 'inherit',
  tableHeaderCellColor: 'inherit',
  //selectPage buttons
  selectPageBorder: '1px solid transparent',
  selectPageBorderRadius: '0.25rem',
  selectPageBackground: 'none',
  selectPageFontFamily: 'inherit',
  selectPageFontSize: 'inherit',
  selectPageFontWeight: undefined,
  selectPageColor: 'inherit',
  selectPageDisabledBorderColor: undefined,
  selectPageDisabledBackground: undefined,
  selectPageDisabledColor: '#666',
  selectPageSelectedBorderColor: '#333',
  selectPageSelectedBackground:
    'linear-gradient(to bottom, #FFF 0%, #CCC 100%)',
  selectPageSelectedColor: '#000',
  selectPageHoveredBorderColor: '#000',
  selectPageHoveredBackground: 'linear-gradient(to bottom, #333 0%, #000 100%)',
  selectPageHoveredColor: '#FFF',
  //selectItemsPerPage
  selectItemsPerPageFontFamily: 'inherit',
  selectItemsPerPageFontSize: 'inherit',
  selectItemsPerPageFontWeight: undefined,
  selectItemsPerPageColor: 'inherit',
  selectItemsPerPageSelectBackground: undefined,
  selectItemsPerPageSelectsColor: undefined,
  selectItemsPerPageBorderRadius: undefined,
  //filter
  filterFontFamily: 'inherit',
  filterFontSize: 'inherit',
  filterFontWeight: undefined,
  filterColor: 'inherit',
  filterInputBackground: undefined,
  filterInputColor: undefined,
  filterBorderRadius: undefined,
  //showDisplayedItems
  showDisplayedItemsFontFamily: 'inherit',
  showDisplayedItemsFontSize: 'inherit',
  showDisplayedItemsFontWeight: undefined,
  showDisplayedItemsColor: 'inherit',
};
