export const userSample = [
  {
    firstName: 'Odile',
    lastName: 'Toche',
    startDate: '2020-05-23',
    department: 'Sales',
    dateOfBirth: '1988-02-21',
    street: '2954 Selah Way',
    city: 'Whiting',
    state: 'VT',
    zipCode: '05778',
  },
  {
    firstName: 'Gilbert',
    lastName: 'Sioux',
    startDate: '2019-12-03',
    department: 'Engineering',
    dateOfBirth: '1974-12-21',
    street: '570 Grand Avenue',
    city: 'Orlando',
    state: 'FL',
    zipCode: '32801',
  },
  {
    firstName: 'Dita',
    lastName: 'Santos',
    startDate: '2020-11-26',
    department: 'Engineering',
    dateOfBirth: '1987-04-16',
    street: '1198 Fantages Way',
    city: 'Lewiston',
    state: 'ME',
    zipCode: '04240',
  },
  {
    firstName: 'Jean-Eudes',
    lastName: 'Cornichon',
    startDate: '2002-02-14',
    department: 'Marketing',
    dateOfBirth: '1971-01-31',
    street: '824 Broadcast Drive',
    city: 'Chantilly',
    state: 'VA',
    zipCode: '22021',
  },
  {
    firstName: 'Marie-Chantal',
    lastName: 'Lalaitière',
    startDate: '1988-09-03',
    department: 'Marketing',
    dateOfBirth: '1970-08-21',
    street: '3131 Irish Lane',
    city: 'Verona',
    state: 'WI',
    zipCode: '53593',
  },
  {
    firstName: 'René',
    lastName: 'Lataupe',
    startDate: '2021-10-19',
    department: 'Legal',
    dateOfBirth: '2001-04-14',
    street: '2939 Hide A Way Road',
    city: 'San Jose',
    state: 'CA',
    zipCode: '95134',
  },
  {
    firstName: 'Jorginio',
    lastName: 'De la Puerta',
    startDate: '2020-01-16',
    department: 'Legal',
    dateOfBirth: '1999-02-11',
    street: '466 E. Oakwood Street',
    city: 'Hialeah',
    state: 'FL',
    zipCode: '33010',
  },
  {
    firstName: 'Isabella',
    lastName: 'Von Carstein',
    startDate: '2017-12-24',
    department: 'Human Resources',
    dateOfBirth: '1992-07-29',
    street: '443 Birchpond Avenue',
    city: 'Pittsburgh',
    state: 'PA',
    zipCode: '15206',
  },
  {
    firstName: 'Baobao',
    lastName: 'Feng',
    startDate: '1987-04-21',
    department: 'Sales',
    dateOfBirth: '1932-04-11',
    street: '8 East Birchwood Street',
    city: 'Danville',
    state: 'VA',
    zipCode: '24540',
  },
  {
    firstName: 'Patrick',
    lastName: 'Sea Star',
    startDate: '1999-09-01',
    department: 'Engineering',
    dateOfBirth: '1970-11-30',
    street: '8151 East Marshall Avenue',
    city: 'Elizabeth',
    state: 'NJ',
    zipCode: '07202',
  },
  {
    firstName: 'Hatake',
    lastName: 'Kakashi',
    startDate: '2010-12-07',
    department: 'Marketing',
    dateOfBirth: '1989-03-31',
    street: '158 Cypress Street',
    city: 'Clementon',
    state: 'NJ',
    zipCode: '08021',
  },
  {
    firstName: "N'golo",
    lastName: 'Kante',
    startDate: '2014-07-07',
    department: 'Engineering',
    dateOfBirth: '1988-07-10',
    street: '8679 San Carlos Street',
    city: 'Media',
    state: 'PA',
    zipCode: '19063',
  },
];
